# Generated by Django 6.0.2 on 2026-04-25 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0004_message"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="input",
            field=models.TextField(max_length=10000),
        ),
    ]
